// Expo config plugin: split the Android build into one APK per ABI.
//
// The debug APK bundles native libraries (React Native / Hermes / Expo, and
// eventually Godot) for every supported architecture. A single *universal* APK
// therefore weighs ~118 MB, which exceeds GitHub's 100 MB per-file limit and
// makes the "commit APK to repo root" step in the CI workflow fail with GH001.
//
// Enabling Gradle's per-ABI split makes `assembleDebug` emit a separate,
// architecture-specific APK (`app-<abi>-debug.apk`) that only carries that
// ABI's `.so` files — each well under the limit. `universalApk false` skips
// the oversized combined APK entirely.
//
// `android/` is regenerated by `expo prebuild` (Continuous Native Generation),
// so this seam is applied as a config plugin instead of editing the generated
// Gradle file directly.
const { withAppBuildGradle } = require('@expo/config-plugins');

const MARKER = '// abi-splits (injected by withAbiSplits config plugin)';
const SPLITS_BLOCK = `
    ${MARKER}
    splits {
        abi {
            reset()
            enable true
            universalApk false
            include "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }
    }
`;

module.exports = function withAbiSplits(config) {
  return withAppBuildGradle(config, (config) => {
    if (config.modResults.language !== 'groovy') {
      throw new Error(
        'withAbiSplits: expected a Groovy android/app/build.gradle',
      );
    }
    let contents = config.modResults.contents;
    if (contents.includes(MARKER)) {
      return config;
    }
    // Inject the splits block as the first statement inside `android { ... }`.
    const replaced = contents.replace(/android\s*\{/, (match) => match + '\n' + SPLITS_BLOCK);
    if (replaced === contents) {
      throw new Error(
        'withAbiSplits: could not find the `android { }` block to patch',
      );
    }
    config.modResults.contents = replaced;
    return config;
  });
};
