// Expo config plugin: make the embedded-Godot AAR resolvable from the *app*.
//
// The `elpian-godot` module declares Godot's embeddable runtime as
// `implementation(name: 'godot-lib.template_release', ext: 'aar')`, backed by a
// `flatDir` repository local to that module (`modules/elpian-godot/android/libs`).
// That local repo resolves the AAR when the module builds itself, but when the
// **app** resolves its aggregated `releaseRuntimeClasspath` (e.g. for
// `lintVitalReportRelease`, a release-only task), the module's `flatDir` is not
// on the app's repository list, so Gradle fails with:
//
//   Could not resolve all dependencies for configuration ':app:releaseRuntimeClasspath'.
//     > Could not find :godot-lib.template_release:.
//         Required by: project :app > project :expo > project :elpian-godot
//
// Declaring the same `flatDir` at the app level makes the AAR resolvable in every
// configuration/task context. `android/` is regenerated by `expo prebuild`
// (Continuous Native Generation), so this is applied as a config plugin instead
// of editing the generated Gradle file.
const { withAppBuildGradle } = require('@expo/config-plugins');

const MARKER = '// godot-lib flatDir (injected by withGodotRepo config plugin)';
// $rootDir is the generated android/ project dir; the module libs sit alongside
// it under react-native/modules/elpian-godot/android/libs.
const REPO_BLOCK = `
${MARKER}
repositories {
    flatDir { dirs "\$rootDir/../modules/elpian-godot/android/libs" }
}
`;

module.exports = function withGodotRepo(config) {
  return withAppBuildGradle(config, (config) => {
    if (config.modResults.language !== 'groovy') {
      throw new Error('withGodotRepo: expected a Groovy android/app/build.gradle');
    }
    const contents = config.modResults.contents;
    if (contents.includes(MARKER)) {
      return config;
    }
    // A top-level repositories block is valid in an app module; append it.
    config.modResults.contents = contents + '\n' + REPO_BLOCK;
    return config;
  });
};
