// Expo config plugin: make the embedded-Godot AAR resolvable from every Gradle
// subproject.
//
// The `elpian-godot` module declares Godot's embeddable runtime as
// `implementation(name: 'godot-lib.template_release', ext: 'aar')`, backed by a
// `flatDir` repository local to that module (`modules/elpian-godot/android/libs`).
// That local repo resolves the AAR when the module builds itself, but every
// project that transitively pulls in `:elpian-godot`'s runtime classpath — the
// `:app` and the `:expo` umbrella module — must also resolve the AAR when it
// builds its own `releaseRuntimeClasspath` (release-only lint tasks force a full
// resolution). Without a repository that hosts the AAR, Gradle fails at
// configuration time with, e.g.:
//
//   Could not resolve all dependencies for configuration ':expo:releaseRuntimeClasspath'.
//     > Could not find :godot-lib.template_release:.
//         Required by: project :expo > project :elpian-godot
//
// Declaring the same `flatDir` in the root `allprojects { repositories { } }`
// makes the AAR resolvable in every subproject and task context — patching a
// single module only moves the failure to the next project up. `android/` is
// regenerated by `expo prebuild` (Continuous Native Generation), so this is
// applied as a config plugin instead of editing the generated Gradle file.
const { withProjectBuildGradle } = require('@expo/config-plugins');

const MARKER = '// godot-lib flatDir (injected by withGodotRepo config plugin)';
// $rootDir is the generated android/ project dir; the module libs sit alongside
// it under react-native/modules/elpian-godot/android/libs.
const REPO_BLOCK = `
${MARKER}
allprojects {
    repositories {
        flatDir { dirs "\$rootDir/../modules/elpian-godot/android/libs" }
    }
}
`;

module.exports = function withGodotRepo(config) {
  return withProjectBuildGradle(config, (config) => {
    if (config.modResults.language !== 'groovy') {
      throw new Error('withGodotRepo: expected a Groovy android/build.gradle');
    }
    const contents = config.modResults.contents;
    if (contents.includes(MARKER)) {
      return config;
    }
    // Appending an extra top-level allprojects block is valid; Gradle merges them.
    config.modResults.contents = contents + '\n' + REPO_BLOCK;
    return config;
  });
};
