#!/usr/bin/env python3
"""Generate the @GlobalScope constant lookup table for the Elpian bridge.

Reads godot-cpp's extension_api.json (the engine's own API dump) and emits
`gen/global_constants_map.inc`: a sorted name->value table plus a binary-search
lookup function. This keeps the bridge's `{"const": "KEY_ESCAPE"}` op complete
by construction — the table is derived from the engine dump, never written by
hand — matching how the rest of the controller reaches the engine via ClassDB.

Covers: top-level global constants and every @GlobalScope enum member
(Key, MouseButton, JoyButton, Error, PropertyHint, Variant.Type spelled
TYPE_*, Side, Corner, Orientation, HorizontalAlignment, ...).

Usage: gen_global_constants.py <extension_api.json> <output.inc>
"""

import json
import sys


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    api = json.load(open(sys.argv[1], encoding="utf-8"))

    entries: dict[str, int] = {}
    for const in api.get("global_constants", []):
        entries[const["name"]] = int(const["value"])
    for enum in api.get("global_enums", []):
        for member in enum.get("values", []):
            # Enum members are already globally-unique spellings (KEY_ESCAPE,
            # MOUSE_BUTTON_LEFT, ...); Variant.Type members arrive as TYPE_*.
            entries[member["name"]] = int(member["value"])

    rows = sorted(entries.items())
    version = api.get("header", {}).get("version_full_name", "unknown")
    with open(sys.argv[2], "w", encoding="utf-8") as out:
        out.write("/* AUTOGENERATED by tools/gen_global_constants.py — do not edit.\n")
        out.write(f" * Source: extension_api.json ({version}), {len(rows)} entries. */\n")
        out.write("#include <cstdint>\n#include <cstring>\n\n")
        out.write("namespace elpian {\n\n")
        out.write("struct GlobalConstantEntry { const char *name; int64_t value; };\n\n")
        out.write("static const GlobalConstantEntry elpian_global_constants[] = {\n")
        for name, value in rows:
            out.write(f'\t{{ "{name}", INT64_C({value}) }},\n')
        out.write("};\n\n")
        out.write(
            "static inline int64_t elpian_lookup_global_constant(const char *name, bool &r_found) {\n"
            "\tsize_t lo = 0, hi = sizeof(elpian_global_constants) / sizeof(elpian_global_constants[0]);\n"
            "\twhile (lo < hi) {\n"
            "\t\tconst size_t mid = lo + (hi - lo) / 2;\n"
            "\t\tconst int cmp = std::strcmp(elpian_global_constants[mid].name, name);\n"
            "\t\tif (cmp == 0) {\n"
            "\t\t\tr_found = true;\n"
            "\t\t\treturn elpian_global_constants[mid].value;\n"
            "\t\t}\n"
            "\t\tif (cmp < 0) {\n"
            "\t\t\tlo = mid + 1;\n"
            "\t\t} else {\n"
            "\t\t\thi = mid;\n"
            "\t\t}\n"
            "\t}\n"
            "\tr_found = false;\n"
            "\treturn 0;\n"
            "}\n\n"
            "} // namespace elpian\n"
        )
    print(f"wrote {sys.argv[2]} with {len(rows)} constants ({version})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
