// ===========================================================================
// GENERATED by tools/build.mjs — do not edit. Source: this Next.js project.
// A single Elpian-JS guest program: godot.js + ui.js + react.js are composed
// ahead of it by the engine; every module below is flattened into one scope.
// ===========================================================================
import 'godot.js';
import 'net.js';
import 'ui.js';
import 'react.js';

// ---- lib/api.jsx ----
// lib/api.jsx — the backend client. Wraps net.js (Net over Godot HTTPRequest)
// with JWT auth, and keeps GameStore in sync. Callback style (the Elpian VM has
// no async/await).

var Api = {};

// Resolve the API origin. On the Godot web export the guest can read the page
// origin through the JavaScriptBridge singleton; otherwise fall back to the
// local dev server.
function detectOrigin() {
  try {
    var jsb = GD.singleton("JavaScriptBridge");
    if (jsb != null) {
      var origin = jsb.call("eval", ["location.origin", true]);
      if (origin != null) {
        var s = "" + origin;
        if (s.indexOf("http") == 0) return s;
      }
    }
  } catch (e) {}
  return "http://localhost:3000";
}
Api.init = function () {
  Net.setBase(detectOrigin());
};
Api.setToken = function (token) {
  GameStore.data.token = token;
  if (token != null) {
    Net.setHeader("Authorization", "Bearer " + token);
  } else {
    Net.setHeader("Authorization", null);
  }
};
function handle(res, cb, errcb) {
  var body = null;
  try {
    body = res.json();
  } catch (e) {
    body = null;
  }
  if (res.ok) {
    if (cb != null) cb(body);
  } else {
    var msg = "Request failed";
    if (body != null && body.message != null) {
      msg = __isType(body.message, "list") ? body.message.join(", ") : "" + body.message;
    } else if (res.status == 0) {
      msg = "Cannot reach server";
    }
    flash(msg, "danger");
    if (errcb != null) errcb(msg);
  }
}
Api.get = function (path, cb, errcb) {
  Net.get("/api" + path, function (res) {
    handle(res, cb, errcb);
  });
};
Api.post = function (path, data, cb, errcb) {
  Net.postJson("/api" + path, data || {}, function (res) {
    handle(res, cb, errcb);
  });
};
Api.patch = function (path, data, cb, errcb) {
  Net.putJson("/api" + path, data || {}, function (res) {
    handle(res, cb, errcb);
  });
};
Api.del = function (path, cb, errcb) {
  Net.del("/api" + path, function (res) {
    handle(res, cb, errcb);
  });
};

// --- high-level flows -------------------------------------------------------

Api.loadConfig = function (cb) {
  Api.get("/config", function (config) {
    GameStore.set({
      config: config
    });
    if (cb != null) cb(config);
  });
};
Api.refreshState = function (cb) {
  Api.get("/cities/me", function (state) {
    GameStore.set({
      state: state,
      me: state.profile
    });
    if (cb != null) cb(state);
  });
};
Api.register = function (email, password, displayName, cb, errcb) {
  Api.post("/auth/register", {
    email: email,
    password: password,
    displayName: displayName
  }, function (r) {
    Api.setToken(r.token);
    GameStore.set({
      me: r.user
    });
    if (cb != null) cb(r);
  }, errcb);
};
Api.login = function (email, password, cb, errcb) {
  Api.post("/auth/login", {
    email: email,
    password: password
  }, function (r) {
    Api.setToken(r.token);
    GameStore.set({
      me: r.user
    });
    if (cb != null) cb(r);
  }, errcb);
};
Api.logout = function () {
  Api.setToken(null);
  GameStore.set({
    state: null,
    me: null
  });
};

// Actions that return the full city state refresh the store automatically.
Api.action = function (path, data, cb) {
  Api.post(path, data, function (state) {
    if (state != null && state.city != null) {
      GameStore.set({
        state: state,
        me: state.profile
      });
    }
    if (cb != null) cb(state);
  });
};

// ---- lib/format.jsx ----
// lib/format.jsx — display helpers and the game's icon/emoji vocabulary.

function fmt(n) {
  var v = Math.floor(n || 0);
  if (Math.abs(v) >= 1000000) return (v / 1000000).toFixed(2) + "M";
  if (Math.abs(v) >= 1000) return (v / 1000).toFixed(1) + "k";
  return "" + v;
}
function signed(n) {
  var v = Math.round((n || 0) * 10) / 10;
  return (v >= 0 ? "+" : "") + v;
}
function fmtDuration(seconds) {
  var s = Math.max(0, Math.floor(seconds));
  var h = Math.floor(s / 3600);
  var m = Math.floor(s % 3600 / 60);
  var sec = s % 60;
  if (h > 0) return h + "h " + m + "m";
  if (m > 0) return m + "m " + sec + "s";
  return sec + "s";
}
function secondsUntil(iso) {
  if (iso == null) return 0;
  var end = new Date(iso).getTime();
  return Math.max(0, Math.floor((end - Date.now()) / 1000));
}
var RES_ICON = {
  lumber: "🪵",
  food: "🌾",
  sulfur: "🟡",
  marble: "🏛️",
  glass: "🔷",
  gold: "🪙",
  iron: "⛓️",
  wine: "🍷"
};
function resIcon(key) {
  return RES_ICON[key] || "•";
}
function resName(key) {
  return ("" + key).charAt(0).toUpperCase() + ("" + key).slice(1);
}
var STAT_ICON = {
  research: "🔬",
  population: "👥",
  populationCap: "🏘️",
  attack: "⚔️",
  defense: "🛡️",
  healing: "➕",
  gems: "💎",
  tradeSlots: "🧾",
  shipSpeed: "🚚",
  score: "⭐",
  rank: "🏆"
};
function statIcon(key) {
  return STAT_ICON[key] || "•";
}
var BUILD_ICON = {
  palace: "🏰",
  municipality: "🏛️",
  university: "🎓",
  laboratory: "⚗️",
  residential: "🏠",
  wheat_fields: "🌾",
  woodworking: "🪓",
  masonry: "🧱",
  glass_workshop: "🔷",
  factory: "🏭",
  bar: "🍻",
  temple: "⛩️",
  market: "🛒",
  barracks: "⚔️",
  police_station: "🚔",
  pharmacy: "💊",
  hospital: "🏥"
};
function buildingIcon(type) {
  return BUILD_ICON[type] || "🏢";
}
var TROOP_ICON = {
  soldier: "🪖",
  rifleman: "🔫",
  commando: "🥷",
  tank: "🛡️",
  helicopter: "🚁",
  war_machine: "🤖",
  doctor: "⚕️"
};
function troopIcon(type) {
  return TROOP_ICON[type] || "🪖";
}

// Map a resource/stat key to a theme colour token for accenting.
function resColor(key) {
  if (key == "gold") return "#ffcf5c";
  if (key == "food") return "#8bd450";
  if (key == "lumber") return "#c58b5a";
  if (key == "iron") return "#9fb0c3";
  if (key == "wine") return "#c0567e";
  if (key == "glass") return "#5ad1e0";
  if (key == "marble") return "#e8e2d0";
  if (key == "sulfur") return "#e6d24a";
  return "#cfd8e3";
}

// ---- lib/router.jsx ----
// lib/router.jsx — a tiny Next.js-style client router for Victor.
//
// There is no server and no URL bar; navigation is in-memory state. The build
// tool scans app/**/page.jsx into a routes manifest and hands it to <VictorApp>,
// which keeps the current path in a useState and renders the matching page
// inside the app layout. `useRouter()` and `<Link>` mirror `next/navigation`.

var RouterContext = createContext(null);

// next/navigation's useRouter(): { path, push(href), back() }.
function useRouter() {
  return useContext(RouterContext);
}

// A navigation button — the Victor analogue of next/link's <Link>.
function Link(props) {
  var router = useRouter();
  var kind = props.active ? "tonal" : "ghost";
  return /*#__PURE__*/_jsx("button", {
    kind: kind,
    onPress: function () {
      router.push(props.href);
    },
    children: props.children
  });
}
function __victorFindRoute(routes, path) {
  for (var i = 0; i < routes.length; i++) {
    if (routes[i].path == path) {
      return routes[i].component;
    }
  }
  return routes[0].component;
}

// The application shell: router state + layout + the active page.
function VictorApp(props) {
  var routes = props.routes;
  var Layout = props.layout;
  var s = useState(props.initial || "/");
  var path = s[0];
  var setPath = s[1];
  var router = useMemo(function () {
    return {
      path: path,
      push: function (to) {
        setPath(to);
      },
      back: function () {
        setPath("/");
      }
    };
  }, [path]);
  var Page = __victorFindRoute(routes, path);
  return /*#__PURE__*/_jsx(RouterContext.Provider, {
    value: router,
    children: /*#__PURE__*/_jsx(Layout, {
      children: /*#__PURE__*/_jsx(Page, {})
    })
  });
}

// ---- lib/store.jsx ----
// lib/store.jsx — a tiny global store with subscribe/notify, plus a React hook
// that re-renders subscribers when the store changes. Written in the Victor
// dialect (no spread/destructuring/template literals; unique global names).

var GameStore = {
  data: {
    token: null,
    config: null,
    // the static rulebook from /api/config
    state: null,
    // the player's full city state from /api/cities/me
    me: null,
    // { displayName, avatar, ... }
    error: null,
    toast: null
  },
  listeners: []
};
GameStore.get = function (key) {
  return GameStore.data[key];
};
GameStore.set = function (patch) {
  var keys = Object.keys(patch);
  for (var i = 0; i < keys.length; i++) {
    GameStore.data[keys[i]] = patch[keys[i]];
  }
  GameStore.notify();
};
GameStore.notify = function () {
  for (var i = 0; i < GameStore.listeners.length; i++) {
    GameStore.listeners[i](GameStore.data);
  }
};
GameStore.subscribe = function (fn) {
  GameStore.listeners.push(fn);
  return function () {
    var idx = GameStore.listeners.indexOf(fn);
    if (idx >= 0) GameStore.listeners.splice(idx, 1);
  };
};

// React hook: returns the live store data and re-renders on any change.
function useGame() {
  var s = useState(0);
  var tick = s[0];
  var setTick = s[1];
  useEffect(function () {
    var unsub = GameStore.subscribe(function () {
      setTick(tick + 1 + Math.random());
    });
    return unsub;
  }, []);
  return GameStore.data;
}

// Show a transient toast message via the store.
function flash(message, kind) {
  GameStore.set({
    toast: {
      message: message,
      kind: kind || "info",
      at: Date.now()
    }
  });
}

// ---- components/Auth.jsx ----
// components/Auth.jsx — the login / register screen and the "name your city"
// setup step shown after registration.

function AuthField(props) {
  return /*#__PURE__*/_jsxs("column", {
    gap: 4,
    children: [/*#__PURE__*/_jsx("caption", {
      color: "muted",
      children: props.label
    }), /*#__PURE__*/_jsx("input", {
      hint: props.hint,
      value: props.value,
      onChange: props.onChange
    })]
  });
}
function AuthGate() {
  var mode = useState("login");
  var email = useState("");
  var pass = useState("");
  var name = useState("");
  var isRegister = mode[0] == "register";
  function submit() {
    if (isRegister) {
      Api.register(email[0], pass[0], name[0], function (r) {
        GameStore.set({
          needsCity: true
        });
      });
    } else {
      Api.login(email[0], pass[0], function (r) {
        if (r.needsCity) {
          GameStore.set({
            needsCity: true
          });
        } else {
          Api.refreshState();
        }
      });
    }
  }
  return /*#__PURE__*/_jsx("center", {
    children: /*#__PURE__*/_jsx("panel", {
      bg: "surface",
      pad: 28,
      radius: 20,
      children: /*#__PURE__*/_jsxs("column", {
        gap: 16,
        children: [/*#__PURE__*/_jsx("title", {
          color: "primary",
          children: "\u2694\uFE0F TRITONIX"
        }), /*#__PURE__*/_jsx("caption", {
          color: "muted",
          children: "Forge an empire on the infinite frontier."
        }), /*#__PURE__*/_jsx("divider", {}), isRegister ? /*#__PURE__*/_jsx(AuthField, {
          label: "Commander name",
          hint: "Your display name",
          value: name[0],
          onChange: name[1]
        }) : null, /*#__PURE__*/_jsx(AuthField, {
          label: "Email",
          hint: "you@realm.com",
          value: email[0],
          onChange: email[1]
        }), /*#__PURE__*/_jsx(AuthField, {
          label: "Password",
          hint: "\u2022\u2022\u2022\u2022\u2022\u2022",
          value: pass[0],
          onChange: pass[1]
        }), /*#__PURE__*/_jsx("button", {
          kind: "filled",
          onPress: submit,
          children: isRegister ? "Found your dynasty" : "Enter the realm"
        }), /*#__PURE__*/_jsx("button", {
          kind: "ghost",
          onPress: function () {
            mode[1](isRegister ? "login" : "register");
          },
          children: isRegister ? "I already have an account" : "Create a new account"
        })]
      })
    })
  });
}
function CitySetup() {
  var name = useState("");
  function found() {
    if (name[0].length < 2) {
      flash("City name must be at least 2 characters", "danger");
      return;
    }
    Api.action("/cities", {
      name: name[0]
    }, function (st) {
      GameStore.set({
        needsCity: false,
        state: st,
        me: st.profile
      });
      flash("Welcome to " + st.city.name + "!", "success");
    });
  }
  return /*#__PURE__*/_jsx("center", {
    children: /*#__PURE__*/_jsx("panel", {
      bg: "surface",
      pad: 28,
      radius: 20,
      children: /*#__PURE__*/_jsxs("column", {
        gap: 16,
        children: [/*#__PURE__*/_jsx("title", {
          color: "primary",
          children: "\uD83C\uDFF0 Found your capital"
        }), /*#__PURE__*/_jsx("caption", {
          color: "muted",
          children: "Choose a name for your first city. It will be placed on the world map among the other realms."
        }), /*#__PURE__*/_jsx("input", {
          hint: "e.g. Rivendell",
          value: name[0],
          onChange: name[1]
        }), /*#__PURE__*/_jsx("button", {
          kind: "filled",
          onPress: found,
          children: "Found city"
        })]
      })
    })
  });
}

// ---- components/CityScene.jsx ----
// components/CityScene.jsx — the 3D city. Buildings are placed on a grid and
// rendered with the Kenney city-builder GLB models (with a coloured platform
// fallback so the scene always reads as a city). The selected building glows.

function catColor(cat) {
  if (cat == "military") return new Color(0.78, 0.35, 0.32, 1.0);
  if (cat == "science") return new Color(0.4, 0.6, 1.0, 1.0);
  if (cat == "economy") return new Color(1.0, 0.82, 0.36, 1.0);
  if (cat == "resource") return new Color(0.55, 0.75, 0.45, 1.0);
  if (cat == "health") return new Color(0.55, 0.85, 0.8, 1.0);
  if (cat == "civic") return new Color(0.75, 0.7, 0.9, 1.0);
  return new Color(0.7, 0.72, 0.78, 1.0);
}
function gridPos(slot) {
  var col = slot % 6;
  var row = Math.floor(slot / 6);
  return [(col - 2.5) * 2.6, 0.0, (row - 1.5) * 2.6];
}

// One building: a platform + the GLB model, scaled a little by level.
function CityBuilding(props) {
  var b = props.building;
  var def = props.def;
  var pos = gridPos(b.slot);
  var selected = props.selectedId == b.id;
  var h = 1.1 + Math.min(2.4, b.level * 0.04);
  var col = catColor(def ? def.category : "civic");
  var src = def ? "res://assets/buildings/" + def.model + ".glb" : null;
  return /*#__PURE__*/_jsxs("node3d", {
    position: pos,
    children: [/*#__PURE__*/_jsx("box", {
      size: [2.2, 0.25, 2.2],
      position: [0.0, 0.12, 0.0],
      color: selected ? new Color(1.0, 0.85, 0.35, 1.0) : new Color(0.22, 0.24, 0.3, 1.0),
      roughness: 0.9
    }), src != null ? /*#__PURE__*/_jsx("gltf", {
      src: src,
      position: [0.0, 0.25, 0.0],
      targetHeight: h
    }) : /*#__PURE__*/_jsx("box", {
      size: [1.4, h, 1.4],
      position: [0.0, 0.25 + h / 2, 0.0],
      color: col
    }), selected ? /*#__PURE__*/_jsx("box", {
      size: [2.4, 0.05, 2.4],
      position: [0.0, 0.02, 0.0],
      color: new Color(1.0, 0.85, 0.35, 1.0),
      emission: new Color(1.0, 0.7, 0.2, 1.0),
      emissionEnergy: 0.8
    }) : null]
  });
}

// A slowly-orbiting camera rig for a pleasant idle presentation.
function CityCamera() {
  var ref = useRef(null);
  var a = useRef(0.0);
  useFrame(function (d) {
    if (ref.current != null) {
      a.current += d * 4.0;
      ref.current.set("rotation_degrees", new Vector3(0.0, a.current, 0.0));
    }
  });
  return /*#__PURE__*/_jsx("node3d", {
    ref: ref,
    children: /*#__PURE__*/_jsx("camera3d", {
      position: [0.0, 9.0, 13.0],
      rotation: [-32, 0, 0],
      fov: 50
    })
  });
}
function CityScene(props) {
  var buildings = props.buildings || [];
  var defByType = props.defByType || {};
  var items = [];
  for (var i = 0; i < buildings.length; i++) {
    var b = buildings[i];
    items.push(/*#__PURE__*/_jsx(CityBuilding, {
      building: b,
      def: defByType[b.type],
      selectedId: props.selectedId
    }, b.id));
  }
  return /*#__PURE__*/_jsxs("scene3d", {
    height: props.height || 380,
    children: [/*#__PURE__*/_jsx("environment", {
      bg: new Color(0.42, 0.62, 0.85, 1.0),
      ambient: new Color(0.7, 0.78, 0.95, 1.0),
      ambientEnergy: 0.85
    }), /*#__PURE__*/_jsx("directionallight", {
      rotation: [-55, -40, 0],
      energy: 1.35,
      color: new Color(1.0, 0.96, 0.86, 1.0)
    }), /*#__PURE__*/_jsx("camera3d", {
      position: [0.0, 9.0, 13.0],
      rotation: [-32, 0, 0],
      fov: 52
    }), /*#__PURE__*/_jsx("plane3d", {
      width: 26,
      depth: 22,
      color: new Color(0.28, 0.5, 0.28, 1.0),
      roughness: 1.0
    }), /*#__PURE__*/_jsx("plane3d", {
      width: 16,
      depth: 12,
      position: [0.0, 0.02, 0.0],
      color: new Color(0.34, 0.34, 0.4, 1.0),
      roughness: 1.0
    }), items]
  });
}

// ---- components/Common.jsx ----
// components/Common.jsx — small shared UI pieces used across every screen.

// A live clock that bumps the store every second (so countdowns tick) and
// refreshes the authoritative city state from the backend a few times a minute.

function Heartbeat() {
  var acc = useState({
    t: 0,
    poll: 0
  });
  useFrame(function (d) {
    var st = acc[0];
    st.t += d;
    st.poll += d;
    if (st.t >= 1.0) {
      st.t = 0;
      GameStore.notify(); // re-render countdowns
    }
    if (st.poll >= 6.0) {
      st.poll = 0;
      if (GameStore.data.token != null && GameStore.data.state != null) {
        Api.refreshState();
      }
    }
  });
  return null;
}

// A transient toast anchored bottom of the screen.
function ToastHost() {
  var g = useGame();
  var t = g.toast;
  if (t == null) return null;
  if (Date.now() - t.at > 3500) return null;
  var kind = t.kind == "danger" ? "danger" : t.kind == "success" ? "primary" : "surface";
  return /*#__PURE__*/_jsx("panel", {
    bg: kind,
    pad: 12,
    radius: 10,
    children: /*#__PURE__*/_jsx("text", {
      color: kind == "surface" ? "text" : "onPrimary",
      children: t.message
    })
  });
}

// A resource pill: icon + amount (+ optional per-minute rate).
function ResChip(props) {
  var rate = props.rate;
  return /*#__PURE__*/_jsxs("row", {
    gap: 4,
    pad: 6,
    children: [/*#__PURE__*/_jsx("text", {
      children: resIcon(props.k)
    }), /*#__PURE__*/_jsxs("column", {
      gap: 0,
      children: [/*#__PURE__*/_jsx("text", {
        color: "text",
        children: fmt(props.amount)
      }), rate != null ? /*#__PURE__*/_jsx("caption", {
        color: rate >= 0 ? "muted" : "danger",
        children: signed(rate) + "/m"
      }) : null]
    })]
  });
}

// The always-visible resource bar (8 resources + gems).
function ResourceBar() {
  var g = useGame();
  if (g.state == null) return null;
  var r = g.state.resources;
  var prod = g.state.economy.production;
  var keys = ["lumber", "food", "sulfur", "marble", "glass", "gold", "iron", "wine"];
  var chips = [];
  for (var i = 0; i < keys.length; i++) {
    chips.push(/*#__PURE__*/_jsx(ResChip, {
      k: keys[i],
      amount: r[keys[i]],
      rate: prod[keys[i]]
    }, keys[i]));
  }
  return /*#__PURE__*/_jsx("panel", {
    bg: "surface",
    pad: 8,
    radius: 12,
    children: /*#__PURE__*/_jsxs("row", {
      gap: 8,
      wrap: true,
      children: [chips, /*#__PURE__*/_jsxs("row", {
        gap: 4,
        pad: 6,
        children: [/*#__PURE__*/_jsx("text", {
          children: "\uD83D\uDC8E"
        }), /*#__PURE__*/_jsx("text", {
          color: "primary",
          children: fmt(g.state.profile.gems)
        })]
      })]
    })
  });
}

// A stat tile (population, research, attack, ...).
function StatTile(props) {
  return /*#__PURE__*/_jsxs("card", {
    gap: 2,
    pad: 10,
    children: [/*#__PURE__*/_jsxs("row", {
      gap: 6,
      children: [/*#__PURE__*/_jsx("text", {
        children: statIcon(props.k)
      }), /*#__PURE__*/_jsx("caption", {
        color: "muted",
        children: props.label
      })]
    }), /*#__PURE__*/_jsx("heading", {
      color: "text",
      children: props.value
    }), props.sub != null ? /*#__PURE__*/_jsx("caption", {
      color: "muted",
      children: props.sub
    }) : null]
  });
}

// A live countdown with an optional gem fast-forward button.
function Countdown(props) {
  useGame(); // subscribe so Heartbeat re-renders us each second
  var secs = secondsUntil(props.endAt);
  return /*#__PURE__*/_jsxs("row", {
    gap: 8,
    children: [/*#__PURE__*/_jsxs("text", {
      color: "muted",
      children: ["\u23F3 ", fmtDuration(secs)]
    }), props.onRush != null && secs > 0 ? /*#__PURE__*/_jsx("button", {
      kind: "tonal",
      onPress: props.onRush,
      children: "💎 Rush"
    }) : null]
  });
}

// A section header.
function Section(props) {
  return /*#__PURE__*/_jsx("row", {
    gap: 8,
    children: /*#__PURE__*/_jsx("heading", {
      color: "text",
      children: props.children
    })
  });
}

// ---- components/Shell.jsx ----
// components/Shell.jsx — the authenticated app frame: top navigation, the
// resource bar, the heartbeat clock and the toast host.

var NAV = [{
  href: "/",
  label: "🏰 City"
}, {
  href: "/world",
  label: "🗺️ World"
}, {
  href: "/research",
  label: "🔬 Research"
}, {
  href: "/military",
  label: "⚔️ Army"
}, {
  href: "/market",
  label: "🛒 Market"
}, {
  href: "/war",
  label: "🔥 Wars"
}, {
  href: "/profile",
  label: "👤 Profile"
}];
function NavButton(props) {
  return /*#__PURE__*/_jsx("button", {
    kind: props.active ? "tonal" : "ghost",
    onPress: props.onPress,
    children: props.label
  });
}
function Shell(props) {
  var router = useRouter();
  var g = useGame();
  var items = [];
  for (var i = 0; i < NAV.length; i++) {
    var n = NAV[i];
    items.push(/*#__PURE__*/_jsx(NavButton, {
      label: n.label,
      active: router.path == n.href,
      onPress: function (href) {
        return function () {
          router.push(href);
        };
      }(n.href)
    }, n.href));
  }
  return /*#__PURE__*/_jsxs("column", {
    gap: 0,
    grow: true,
    children: [/*#__PURE__*/_jsx(Heartbeat, {}), /*#__PURE__*/_jsx("panel", {
      bg: "surface",
      pad: 10,
      children: /*#__PURE__*/_jsxs("column", {
        gap: 8,
        children: [/*#__PURE__*/_jsxs("row", {
          gap: 8,
          children: [/*#__PURE__*/_jsx("title", {
            color: "primary",
            children: "TRITONIX"
          }), /*#__PURE__*/_jsx("spacer", {}), /*#__PURE__*/_jsx("text", {
            color: "muted",
            children: g.state != null ? "🏙️ " + g.state.city.name : ""
          }), /*#__PURE__*/_jsx("button", {
            kind: "ghost",
            onPress: function () {
              Api.logout();
            },
            children: "Log out"
          })]
        }), /*#__PURE__*/_jsx("row", {
          gap: 6,
          wrap: true,
          children: items
        }), /*#__PURE__*/_jsx(ResourceBar, {})]
      })
    }), /*#__PURE__*/_jsxs("scroll", {
      gap: 16,
      pad: 16,
      children: [props.children, /*#__PURE__*/_jsx(ToastHost, {})]
    })]
  });
}

// ---- components/WorldScene.jsx ----
// components/WorldScene.jsx — the 3D world map. Terrain is procedurally
// generated from tile coordinates (value noise seeded by the shared WORLD_SEED),
// producing lakes, deserts, forests, jungles and mountains. Player cities from
// the backend are drawn as markers on top.

var WSEED = 1337;
function hash2(x, y) {
  var n = Math.sin(x * 127.1 + y * 311.7 + WSEED * 0.013) * 43758.5453;
  return n - Math.floor(n);
}
function smooth(t) {
  return t * t * (3 - 2 * t);
}
function valueNoise(x, y) {
  var xi = Math.floor(x);
  var yi = Math.floor(y);
  var xf = x - xi;
  var yf = y - yi;
  var a = hash2(xi, yi);
  var b = hash2(xi + 1, yi);
  var c = hash2(xi, yi + 1);
  var d = hash2(xi + 1, yi + 1);
  var u = smooth(xf);
  var v = smooth(yf);
  return a * (1 - u) * (1 - v) + b * u * (1 - v) + c * (1 - u) * v + d * u * v;
}
function elevationAt(tx, ty) {
  var e = valueNoise(tx * 0.12, ty * 0.12) * 0.6 + valueNoise(tx * 0.3, ty * 0.3) * 0.4;
  return e;
}
function moistureAt(tx, ty) {
  return valueNoise((tx + 500) * 0.09, (ty - 500) * 0.09);
}

// biome -> { color, height }
function biome(tx, ty) {
  var e = elevationAt(tx, ty);
  var m = moistureAt(tx, ty);
  if (e < 0.34) return {
    color: new Color(0.2, 0.45, 0.72, 1.0),
    h: 0.08,
    kind: "lake"
  };
  if (e < 0.44 && m < 0.4) return {
    color: new Color(0.85, 0.78, 0.5, 1.0),
    h: 0.18,
    kind: "desert"
  };
  if (e < 0.62) {
    if (m > 0.6) return {
      color: new Color(0.16, 0.45, 0.2, 1.0),
      h: 0.28,
      kind: "jungle"
    };
    return {
      color: new Color(0.32, 0.58, 0.3, 1.0),
      h: 0.24,
      kind: "forest"
    };
  }
  if (e < 0.78) return {
    color: new Color(0.45, 0.42, 0.36, 1.0),
    h: 0.6 + e,
    kind: "hill"
  };
  return {
    color: new Color(0.6, 0.6, 0.63, 1.0),
    h: 1.2 + e * 1.4,
    kind: "mountain"
  };
}
var STEP = 1.7;
var HALF = 8; // 17x17 tiles

function TerrainTile(props) {
  var b = props.b;
  var showTree = (b.kind == "forest" || b.kind == "jungle") && props.decorate;
  return /*#__PURE__*/_jsxs("node3d", {
    position: props.pos,
    children: [/*#__PURE__*/_jsx("box", {
      size: [STEP, b.h, STEP],
      position: [0.0, b.h / 2, 0.0],
      color: b.color,
      roughness: 1.0
    }), showTree ? /*#__PURE__*/_jsx("box", {
      size: [0.35, 0.7, 0.35],
      position: [0.3, b.h + 0.35, 0.3],
      color: new Color(0.12, 0.35, 0.15, 1.0)
    }) : null]
  });
}
function CityMarker(props) {
  var c = props.city;
  var ref = useRef(null);
  useFrame(function (d) {
    if (ref.current != null) {
      ref.current.set("rotation_degrees", new Vector3(0.0, Date.now() / 20 % 360, 0.0));
    }
  });
  var col = props.mine ? new Color(1.0, 0.82, 0.3, 1.0) : props.selected ? new Color(1.0, 0.4, 0.4, 1.0) : new Color(0.85, 0.3, 0.3, 1.0);
  return /*#__PURE__*/_jsxs("node3d", {
    position: props.pos,
    ref: ref,
    children: [/*#__PURE__*/_jsx("box", {
      size: [0.7, 1.6, 0.7],
      position: [0.0, 1.4, 0.0],
      color: col,
      emission: col,
      emissionEnergy: props.selected ? 0.9 : 0.35
    }), /*#__PURE__*/_jsx("box", {
      size: [1.2, 0.2, 1.2],
      position: [0.0, 0.6, 0.0],
      color: col
    })]
  });
}
function WorldScene(props) {
  var center = props.center || {
    x: 0,
    y: 0
  };
  var cities = props.cities || [];
  var tiles = [];
  for (var dx = -HALF; dx <= HALF; dx++) {
    for (var dy = -HALF; dy <= HALF; dy++) {
      var tx = center.x + dx;
      var ty = center.y + dy;
      var b = biome(tx, ty);
      var decorate = (dx + dy) % 2 == 0;
      tiles.push(/*#__PURE__*/_jsx(TerrainTile, {
        b: b,
        decorate: decorate,
        pos: [dx * STEP, 0.0, dy * STEP]
      }, "t-" + dx + "-" + dy));
    }
  }
  var markers = [];
  for (var i = 0; i < cities.length; i++) {
    var c = cities[i];
    var mdx = c.x - center.x;
    var mdy = c.y - center.y;
    if (Math.abs(mdx) > HALF || Math.abs(mdy) > HALF) continue;
    var bb = biome(c.x, c.y);
    markers.push(/*#__PURE__*/_jsx(CityMarker, {
      city: c,
      mine: c.id == props.myCityId,
      selected: c.id == props.selectedId,
      pos: [mdx * STEP, bb.h, mdy * STEP]
    }, "c-" + c.id));
  }
  return /*#__PURE__*/_jsxs("scene3d", {
    height: props.height || 420,
    children: [/*#__PURE__*/_jsx("environment", {
      bg: new Color(0.5, 0.68, 0.9, 1.0),
      ambient: new Color(0.75, 0.82, 0.95, 1.0),
      ambientEnergy: 0.9
    }), /*#__PURE__*/_jsx("directionallight", {
      rotation: [-60, -35, 0],
      energy: 1.3,
      color: new Color(1.0, 0.97, 0.88, 1.0)
    }), /*#__PURE__*/_jsx("camera3d", {
      position: [0.0, 22.0, 20.0],
      rotation: [-48, 0, 0],
      fov: 55
    }), tiles, markers]
  });
}

// ---- app/layout.jsx ----
// app/layout.jsx — the root layout. Boots the config, gates on authentication
// and city creation, then wraps every page in the authenticated Shell.

function __layout__root(props) {
  var g = useGame();
  var booted = useState(false);
  useEffect(function () {
    Api.init();
    Api.loadConfig(function () {
      booted[1](true);
    });
  }, []);

  // Once authenticated with a city but no state yet, fetch it (post-render).
  useEffect(function () {
    if (g.token != null && !g.needsCity && g.state == null && g.me != null) {
      Api.refreshState();
    }
  }, [g.token, g.needsCity, g.state, g.me]);
  if (!booted[0] || g.config == null) {
    return /*#__PURE__*/_jsx("center", {
      children: /*#__PURE__*/_jsxs("column", {
        gap: 12,
        children: [/*#__PURE__*/_jsx("title", {
          color: "primary",
          children: "\u2694\uFE0F TRITONIX"
        }), /*#__PURE__*/_jsx("caption", {
          color: "muted",
          children: "Loading the realm\u2026"
        })]
      })
    });
  }
  if (g.token == null) {
    return /*#__PURE__*/_jsx(AuthGate, {});
  }
  if (g.needsCity || g.state == null && g.me == null) {
    return /*#__PURE__*/_jsx(CitySetup, {});
  }
  if (g.state == null) {
    return /*#__PURE__*/_jsx("center", {
      children: /*#__PURE__*/_jsx("caption", {
        color: "muted",
        children: "Entering your city\u2026"
      })
    });
  }
  return /*#__PURE__*/_jsx(Shell, {
    children: props.children
  });
}

// ---- app/market/page.jsx ----
// app/market/page.jsx — the marketplace: create trade offers and buy from
// offers posted by other cities.

var RES = ["lumber", "food", "sulfur", "marble", "glass", "gold", "iron", "wine"];
function ResSelect(props) {
  // A simple resource picker rendered as a row of chips.
  var chips = [];
  for (var i = 0; i < RES.length; i++) {
    var r = RES[i];
    chips.push(/*#__PURE__*/_jsx("button", {
      kind: props.value == r ? "tonal" : "ghost",
      onPress: function (rr) {
        return function () {
          props.onChange(rr);
        };
      }(r),
      children: resIcon(r)
    }, r));
  }
  return /*#__PURE__*/_jsx("row", {
    gap: 4,
    wrap: true,
    children: chips
  });
}
function CreateOffer(props) {
  var give = useState("gold");
  var giveAmt = useState("100");
  var want = useState("iron");
  var wantAmt = useState("50");
  function create() {
    Api.post("/market/offers", {
      give: give[0],
      giveAmount: parseInt(giveAmt[0], 10) || 0,
      want: want[0],
      wantAmount: parseInt(wantAmt[0], 10) || 0
    }, function () {
      flash("Offer posted", "success");
      props.reload();
      Api.refreshState();
    });
  }
  return /*#__PURE__*/_jsxs("card", {
    gap: 10,
    children: [/*#__PURE__*/_jsx(Section, {
      children: "Create offer"
    }), /*#__PURE__*/_jsx("caption", {
      color: "muted",
      children: "Offer (give)"
    }), /*#__PURE__*/_jsx(ResSelect, {
      value: give[0],
      onChange: give[1]
    }), /*#__PURE__*/_jsx("input", {
      hint: "give amount",
      value: giveAmt[0],
      onChange: giveAmt[1]
    }), /*#__PURE__*/_jsx("caption", {
      color: "muted",
      children: "In return for (want)"
    }), /*#__PURE__*/_jsx(ResSelect, {
      value: want[0],
      onChange: want[1]
    }), /*#__PURE__*/_jsx("input", {
      hint: "want amount",
      value: wantAmt[0],
      onChange: wantAmt[1]
    }), /*#__PURE__*/_jsx("button", {
      kind: "filled",
      onPress: create,
      children: "Post offer"
    })]
  });
}
function OfferRow(props) {
  var o = props.offer;
  var units = useState("");
  function accept() {
    var n = parseInt(units[0], 10) || o.remaining;
    Api.post("/market/offers/" + o.id + "/accept", {
      units: n
    }, function (r) {
      flash("Bought " + r.bought + " " + o.give + " for " + r.paid + " " + o.want, "success");
      props.reload();
      Api.refreshState();
    });
  }
  function cancel() {
    Api.del("/market/offers/" + o.id, function () {
      flash("Offer cancelled", "info");
      props.reload();
      Api.refreshState();
    });
  }
  return /*#__PURE__*/_jsxs("card", {
    gap: 6,
    children: [/*#__PURE__*/_jsxs("row", {
      gap: 8,
      wrap: true,
      children: [/*#__PURE__*/_jsx("text", {
        color: "text",
        children: resIcon(o.give) + " " + fmt(o.remaining) + " " + resName(o.give)
      }), /*#__PURE__*/_jsx("text", {
        color: "muted",
        children: "\u2192"
      }), /*#__PURE__*/_jsx("text", {
        color: "text",
        children: resIcon(o.want) + " " + fmt(o.wantAmount) + " per " + fmt(o.giveAmount)
      }), /*#__PURE__*/_jsx("spacer", {}), /*#__PURE__*/_jsx("caption", {
        color: "muted",
        children: o.sellerCity
      })]
    }), o.mine ? /*#__PURE__*/_jsx("button", {
      kind: "danger",
      onPress: cancel,
      children: "Cancel"
    }) : /*#__PURE__*/_jsxs("row", {
      gap: 8,
      children: [/*#__PURE__*/_jsx("input", {
        hint: "units (max " + fmt(o.remaining) + ")",
        value: units[0],
        onChange: units[1]
      }), /*#__PURE__*/_jsx("button", {
        kind: "filled",
        onPress: accept,
        children: "Buy"
      })]
    })]
  });
}
function __page__market() {
  var offers = useState([]);
  function reload() {
    Api.get("/market/offers", function (list) {
      offers[1](list);
    });
  }
  useEffect(function () {
    reload();
  }, []);
  var rows = [];
  for (var i = 0; i < offers[0].length; i++) rows.push(/*#__PURE__*/_jsx(OfferRow, {
    offer: offers[0][i],
    reload: reload
  }, offers[0][i].id));
  return /*#__PURE__*/_jsxs("column", {
    gap: 16,
    children: [/*#__PURE__*/_jsx(Section, {
      children: "Marketplace"
    }), /*#__PURE__*/_jsx(CreateOffer, {
      reload: reload
    }), /*#__PURE__*/_jsx(Section, {
      children: "Open offers"
    }), rows.length > 0 ? rows : /*#__PURE__*/_jsx("caption", {
      color: "muted",
      children: "No offers yet \u2014 be the first to trade."
    })]
  });
}

// ---- app/military/page.jsx ----
// app/military/page.jsx — the barracks: garrison overview and troop training.

function TroopCard(props) {
  var t = props.troop;
  var count = useState("10");
  function train() {
    var n = parseInt(count[0], 10);
    if (isNaN(n) || n < 1) n = 1;
    Api.action("/military/train", {
      troopType: t.key,
      count: n
    });
  }
  var costKeys = Object.keys(t.cost);
  var costChips = [];
  for (var i = 0; i < costKeys.length; i++) {
    costChips.push(/*#__PURE__*/_jsx("caption", {
      color: "muted",
      children: (resIcon(costKeys[i]) || costKeys[i]) + " " + t.cost[costKeys[i]]
    }, costKeys[i]));
  }
  return /*#__PURE__*/_jsxs("card", {
    gap: 6,
    children: [/*#__PURE__*/_jsxs("row", {
      gap: 8,
      children: [/*#__PURE__*/_jsx("title", {
        color: "text",
        children: troopIcon(t.key) + " " + t.name
      }), /*#__PURE__*/_jsx("spacer", {}), /*#__PURE__*/_jsx("badge", {
        children: "You have " + fmt(props.owned)
      })]
    }), /*#__PURE__*/_jsx("text", {
      wrap: true,
      color: "muted",
      children: t.description
    }), /*#__PURE__*/_jsxs("row", {
      gap: 12,
      wrap: true,
      children: [/*#__PURE__*/_jsx("caption", {
        color: "muted",
        children: "⚔️ " + t.attack
      }), /*#__PURE__*/_jsx("caption", {
        color: "muted",
        children: "🛡️ " + t.defense
      }), /*#__PURE__*/_jsx("caption", {
        color: "muted",
        children: "❤️ " + t.health
      }), /*#__PURE__*/_jsx("caption", {
        color: "muted",
        children: "🎒 " + t.carry
      }), /*#__PURE__*/_jsx("caption", {
        color: "muted",
        children: "⏳ " + fmtDuration(t.trainTime) + "/unit"
      })]
    }), /*#__PURE__*/_jsx("row", {
      gap: 10,
      wrap: true,
      children: costChips
    }), t.unlocked ? /*#__PURE__*/_jsxs("row", {
      gap: 8,
      children: [/*#__PURE__*/_jsx("input", {
        hint: "count",
        value: count[0],
        onChange: count[1]
      }), /*#__PURE__*/_jsx("button", {
        kind: "filled",
        onPress: train,
        children: "Train"
      })]
    }) : /*#__PURE__*/_jsx("caption", {
      color: "danger",
      children: "🔒 Barracks L" + t.requiresBarracks + (t.requiresResearch.length ? " + " + t.requiresResearch.join(", ") : "")
    })]
  });
}
function __page__military() {
  var g = useGame();
  var troops = useState([]);
  useEffect(function () {
    Api.get("/military", function (list) {
      troops[1](list);
    });
  }, []);
  var owned = {};
  for (var i = 0; i < g.state.troops.length; i++) owned[g.state.troops[i].type] = g.state.troops[i].count;
  var active = null;
  for (var k = 0; k < g.state.jobs.length; k++) if (g.state.jobs[k].kind == "TRAIN") active = g.state.jobs[k];
  var cards = [];
  for (var j = 0; j < troops[0].length; j++) {
    var t = troops[0][j];
    cards.push(/*#__PURE__*/_jsx(TroopCard, {
      troop: t,
      owned: owned[t.key] || 0
    }, t.key));
  }
  return /*#__PURE__*/_jsxs("column", {
    gap: 16,
    children: [/*#__PURE__*/_jsx(Section, {
      children: "Army & training"
    }), /*#__PURE__*/_jsx("caption", {
      color: "muted",
      children: "Army attack power: " + fmt(g.state.economy.attack) + "  ·  City defense: " + fmt(g.state.economy.defense)
    }), active != null ? /*#__PURE__*/_jsx("card", {
      gap: 8,
      children: /*#__PURE__*/_jsxs("row", {
        gap: 8,
        children: [/*#__PURE__*/_jsx("text", {
          grow: true,
          color: "text",
          children: "🪖 Training " + active.count + "× " + active.troopType
        }), /*#__PURE__*/_jsx(Countdown, {
          endAt: active.endAt,
          onRush: function () {
            Api.post("/gems/fastforward", {
              kind: "job",
              id: active.id
            }, function () {
              Api.refreshState();
            });
          }
        })]
      })
    }) : null, cards]
  });
}

// ---- app/page.jsx ----
// app/page.jsx — the City screen. The 3D city, the construction queue, the
// building roster and the build/upgrade/downgrade/destruct controls.

function defMap(config) {
  var m = {};
  for (var i = 0; i < config.buildings.length; i++) m[config.buildings[i].key] = config.buildings[i];
  return m;
}
function CostRow(props) {
  var cost = props.cost || {};
  var keys = Object.keys(cost);
  var chips = [];
  for (var i = 0; i < keys.length; i++) {
    chips.push(/*#__PURE__*/_jsx("text", {
      color: "muted",
      children: resIcon(keys[i]) + " " + fmt(cost[keys[i]])
    }, keys[i]));
  }
  return /*#__PURE__*/_jsx("row", {
    gap: 10,
    wrap: true,
    children: chips
  });
}
function ReqRow(props) {
  var req = props.req;
  if (req == null) return null;
  var parts = [];
  if (req.palace > 0) parts.push("🏰 Palace " + req.palace);
  var bks = Object.keys(req.buildings || {});
  for (var i = 0; i < bks.length; i++) parts.push(buildingIcon(bks[i]) + " " + bks[i] + " " + req.buildings[bks[i]]);
  for (var j = 0; j < (req.research || []).length; j++) parts.push("🔬 " + req.research[j]);
  if (parts.length == 0) return null;
  return /*#__PURE__*/_jsx("caption", {
    color: "muted",
    children: "Requires: " + parts.join("  ·  ")
  });
}

// The active construction/research/training queue.
function JobQueue() {
  var g = useGame();
  var jobs = g.state.jobs || [];
  if (jobs.length == 0) return null;
  var rows = [];
  for (var i = 0; i < jobs.length; i++) {
    rows.push(/*#__PURE__*/_jsx(JobRow, {
      job: jobs[i]
    }, jobs[i].id));
  }
  return /*#__PURE__*/_jsxs("card", {
    gap: 10,
    children: [/*#__PURE__*/_jsx(Section, {
      children: "Active queue"
    }), rows]
  });
}
function JobRow(props) {
  var j = props.job;
  var label = "";
  if (j.kind == "BUILD") label = "🔨 Build " + j.buildType;else if (j.kind == "UPGRADE") label = "⬆️ Upgrade to L" + j.toLevel;else if (j.kind == "DOWNGRADE") label = "⬇️ Downgrade to L" + j.toLevel;else if (j.kind == "DESTRUCT") label = "💥 Demolish";else if (j.kind == "RESEARCH") label = "🔬 Research " + j.topicKey;else if (j.kind == "TRAIN") label = "🪖 Train " + j.count + "× " + j.troopType;
  function rush() {
    Api.post("/gems/fastforward", {
      kind: "job",
      id: j.id
    }, function () {
      Api.refreshState();
    });
  }
  return /*#__PURE__*/_jsxs("row", {
    gap: 10,
    children: [/*#__PURE__*/_jsx("text", {
      grow: true,
      color: "text",
      children: label
    }), /*#__PURE__*/_jsx(Countdown, {
      endAt: j.endAt,
      onRush: rush
    })]
  });
}
function SelectedBuilding(props) {
  var b = props.building;
  var info = props.info;
  function upgrade() {
    Api.action("/buildings/" + b.id + "/upgrade");
  }
  function downgrade() {
    Api.action("/buildings/" + b.id + "/downgrade");
  }
  function destruct() {
    Api.action("/buildings/" + b.id + "/destruct");
  }
  var def = props.def;
  return /*#__PURE__*/_jsxs("card", {
    gap: 10,
    children: [/*#__PURE__*/_jsxs("row", {
      gap: 8,
      children: [/*#__PURE__*/_jsx("title", {
        color: "text",
        children: buildingIcon(b.type) + " " + (def ? def.name : b.type)
      }), /*#__PURE__*/_jsx("spacer", {}), /*#__PURE__*/_jsx("badge", {
        children: "Level " + b.level
      })]
    }), def ? /*#__PURE__*/_jsx("text", {
      wrap: true,
      color: "muted",
      children: def.description
    }) : null, /*#__PURE__*/_jsx("divider", {}), /*#__PURE__*/_jsx("caption", {
      color: "muted",
      children: "Current output"
    }), /*#__PURE__*/_jsx(ImpactRow, {
      impact: b.impact
    }), info != null && info.next != null ? /*#__PURE__*/_jsxs("column", {
      gap: 8,
      children: [/*#__PURE__*/_jsx("divider", {}), /*#__PURE__*/_jsx("caption", {
        color: "primary",
        children: "Upgrade to Level " + info.next.level
      }), /*#__PURE__*/_jsx(CostRow, {
        cost: info.next.cost
      }), /*#__PURE__*/_jsx("caption", {
        color: "muted",
        children: "⏳ " + fmtDuration(info.next.time)
      }), /*#__PURE__*/_jsx(ReqRow, {
        req: info.next.requirement
      }), /*#__PURE__*/_jsxs("row", {
        gap: 8,
        children: [/*#__PURE__*/_jsx("button", {
          kind: "filled",
          onPress: upgrade,
          children: "Upgrade"
        }), b.level > 1 ? /*#__PURE__*/_jsx("button", {
          kind: "outline",
          onPress: downgrade,
          children: "Downgrade"
        }) : null, b.type != "palace" ? /*#__PURE__*/_jsx("button", {
          kind: "danger",
          onPress: destruct,
          children: "Demolish"
        }) : null]
      })]
    }) : /*#__PURE__*/_jsx("caption", {
      color: "muted",
      children: "Max level reached."
    })]
  });
}
function ImpactRow(props) {
  var imp = props.impact || {};
  var keys = Object.keys(imp);
  var parts = [];
  for (var i = 0; i < keys.length; i++) {
    if (imp[keys[i]] == 0) continue;
    var lbl = keys[i];
    parts.push(/*#__PURE__*/_jsx("caption", {
      color: "muted",
      children: lbl + ": +" + fmt(imp[keys[i]])
    }, keys[i]));
  }
  if (parts.length == 0) return /*#__PURE__*/_jsx("caption", {
    color: "muted",
    children: "\u2014"
  });
  return /*#__PURE__*/_jsx("row", {
    gap: 12,
    wrap: true,
    children: parts
  });
}
function BuildNew(props) {
  var g = useGame();
  var config = g.config;
  var existing = {};
  for (var i = 0; i < g.state.buildings.length; i++) existing[g.state.buildings[i].type] = true;
  var dm = defMap(config);
  var cards = [];
  for (var t = 0; t < config.buildingTypes.length; t++) {
    var type = config.buildingTypes[t];
    if (existing[type]) continue;
    cards.push(/*#__PURE__*/_jsx(BuildOption, {
      type: type,
      def: dm[type]
    }, type));
  }
  if (cards.length == 0) return null;
  return /*#__PURE__*/_jsxs("card", {
    gap: 10,
    children: [/*#__PURE__*/_jsx(Section, {
      children: "Construct new building"
    }), cards]
  });
}
function BuildOption(props) {
  var type = props.type;
  var def = props.def;
  var opened = useState(null);
  function load() {
    Api.get("/buildings/" + type + "/info", function (info) {
      opened[1](info);
    });
  }
  function build() {
    Api.action("/buildings/build", {
      type: type
    });
    opened[1](null);
  }
  return /*#__PURE__*/_jsxs("column", {
    gap: 6,
    children: [/*#__PURE__*/_jsxs("row", {
      gap: 8,
      children: [/*#__PURE__*/_jsx("text", {
        grow: true,
        color: "text",
        children: buildingIcon(type) + " " + (def ? def.name : type)
      }), /*#__PURE__*/_jsx("button", {
        kind: "tonal",
        onPress: load,
        children: "Details"
      }), /*#__PURE__*/_jsx("button", {
        kind: "filled",
        onPress: build,
        children: "Build"
      })]
    }), opened[0] != null && opened[0].next != null ? /*#__PURE__*/_jsxs("column", {
      gap: 4,
      pad: 6,
      children: [/*#__PURE__*/_jsx("text", {
        wrap: true,
        color: "muted",
        children: def ? def.description : ""
      }), /*#__PURE__*/_jsx(CostRow, {
        cost: opened[0].next.cost
      }), /*#__PURE__*/_jsx("caption", {
        color: "muted",
        children: "⏳ " + fmtDuration(opened[0].next.time)
      }), /*#__PURE__*/_jsx(ReqRow, {
        req: opened[0].next.requirement
      })]
    }) : null]
  });
}
function __page__index() {
  var g = useGame();
  var sel = useState(null); // { building, info }
  var dm = defMap(g.config);
  function select(b) {
    sel[1]({
      building: b,
      info: null
    });
    Api.get("/buildings/" + b.type + "/info", function (info) {
      sel[1]({
        building: b,
        info: info
      });
    });
  }
  var buildingRows = [];
  for (var i = 0; i < g.state.buildings.length; i++) {
    var b = g.state.buildings[i];
    buildingRows.push(/*#__PURE__*/_jsx(BuildingRow, {
      building: b,
      def: dm[b.type],
      onSelect: select,
      selected: sel[0] != null && sel[0].building.id == b.id
    }, b.id));
  }
  var econ = g.state.economy;
  return /*#__PURE__*/_jsxs("column", {
    gap: 16,
    children: [/*#__PURE__*/_jsx(CityScene, {
      buildings: g.state.buildings,
      defByType: dm,
      selectedId: sel[0] != null ? sel[0].building.id : null,
      height: 360
    }), /*#__PURE__*/_jsxs("row", {
      gap: 10,
      wrap: true,
      children: [/*#__PURE__*/_jsx(StatTile, {
        k: "population",
        label: "Population",
        value: fmt(g.state.city.population),
        sub: "/ " + fmt(econ.populationCap)
      }), /*#__PURE__*/_jsx(StatTile, {
        k: "research",
        label: "Research pts",
        value: fmt(g.state.city.researchBank),
        sub: "+" + fmt(econ.researchPerMin) + "/m"
      }), /*#__PURE__*/_jsx(StatTile, {
        k: "attack",
        label: "Attack pwr",
        value: fmt(econ.attack)
      }), /*#__PURE__*/_jsx(StatTile, {
        k: "defense",
        label: "Defense pwr",
        value: fmt(econ.defense)
      })]
    }), /*#__PURE__*/_jsx(JobQueue, {}), /*#__PURE__*/_jsxs("card", {
      gap: 8,
      children: [/*#__PURE__*/_jsx(Section, {
        children: "Your buildings"
      }), buildingRows]
    }), sel[0] != null ? /*#__PURE__*/_jsx(SelectedBuilding, {
      building: sel[0].building,
      info: sel[0].info,
      def: dm[sel[0].building.type]
    }) : null, /*#__PURE__*/_jsx(BuildNew, {})]
  });
}
function BuildingRow(props) {
  var b = props.building;
  var def = props.def;
  return /*#__PURE__*/_jsxs("row", {
    gap: 8,
    children: [/*#__PURE__*/_jsx("text", {
      grow: true,
      color: props.selected ? "primary" : "text",
      children: buildingIcon(b.type) + " " + (def ? def.name : b.type)
    }), /*#__PURE__*/_jsx("badge", {
      children: "L" + b.level
    }), /*#__PURE__*/_jsx("button", {
      kind: props.selected ? "tonal" : "ghost",
      onPress: function () {
        props.onSelect(b);
      },
      children: "Manage"
    })]
  });
}

// ---- app/profile/page.jsx ----
// app/profile/page.jsx — the player's profile (editable) and the leaderboard.

var AVATARS = ["avatar-1", "avatar-2", "avatar-3", "avatar-4", "avatar-5", "avatar-6"];
var AVATAR_GLYPH = {
  "avatar-1": "🧙",
  "avatar-2": "👑",
  "avatar-3": "🛡️",
  "avatar-4": "⚔️",
  "avatar-5": "🦉",
  "avatar-6": "🐉"
};
function AvatarPicker(props) {
  var chips = [];
  for (var i = 0; i < AVATARS.length; i++) {
    var a = AVATARS[i];
    chips.push(/*#__PURE__*/_jsx("button", {
      kind: props.value == a ? "tonal" : "ghost",
      onPress: function (aa) {
        return function () {
          props.onChange(aa);
        };
      }(a),
      children: AVATAR_GLYPH[a]
    }, a));
  }
  return /*#__PURE__*/_jsx("row", {
    gap: 6,
    wrap: true,
    children: chips
  });
}
function MyProfile() {
  var g = useGame();
  var me = useState(null);
  var bio = useState("");
  var avatar = useState("avatar-1");
  useEffect(function () {
    Api.get("/players/" + (g.me.id || ""), function (p) {
      me[1](p);
      bio[1](p.bio || "");
      avatar[1](p.avatar || "avatar-1");
    });
  }, []);
  function save() {
    Api.patch("/profile", {
      bio: bio[0],
      avatar: avatar[0]
    }, function (p) {
      me[1](p);
      flash("Profile saved", "success");
      Api.refreshState();
    });
  }
  return /*#__PURE__*/_jsxs("card", {
    gap: 10,
    children: [/*#__PURE__*/_jsx(Section, {
      children: "Your profile"
    }), /*#__PURE__*/_jsxs("row", {
      gap: 10,
      children: [/*#__PURE__*/_jsx("title", {
        color: "text",
        children: AVATAR_GLYPH[avatar[0]] + " " + g.me.displayName
      }), /*#__PURE__*/_jsx("spacer", {}), me[0] != null ? /*#__PURE__*/_jsx("badge", {
        children: "#" + me[0].rank
      }) : null]
    }), /*#__PURE__*/_jsxs("row", {
      gap: 12,
      wrap: true,
      children: [/*#__PURE__*/_jsx("caption", {
        color: "muted",
        children: "⭐ Score " + fmt(g.me.score)
      }), /*#__PURE__*/_jsx("caption", {
        color: "muted",
        children: "💎 Gems " + fmt(g.me.gems)
      }), /*#__PURE__*/_jsx("caption", {
        color: "muted",
        children: "🏙️ " + g.state.city.name + " @ (" + g.state.city.x + ", " + g.state.city.y + ")"
      })]
    }), /*#__PURE__*/_jsx("caption", {
      color: "muted",
      children: "Avatar"
    }), /*#__PURE__*/_jsx(AvatarPicker, {
      value: avatar[0],
      onChange: avatar[1]
    }), /*#__PURE__*/_jsx("caption", {
      color: "muted",
      children: "Bio"
    }), /*#__PURE__*/_jsx("textarea", {
      hint: "Tell the realm about yourself",
      value: bio[0],
      onChange: bio[1]
    }), /*#__PURE__*/_jsx("button", {
      kind: "filled",
      onPress: save,
      children: "Save profile"
    })]
  });
}
function Leaderboard() {
  var board = useState([]);
  useEffect(function () {
    Api.get("/leaderboard", function (list) {
      board[1](list);
    });
  }, []);
  var rows = [];
  for (var i = 0; i < board[0].length; i++) {
    var r = board[0][i];
    rows.push(/*#__PURE__*/_jsxs("row", {
      gap: 8,
      children: [/*#__PURE__*/_jsx("text", {
        color: i < 3 ? "primary" : "text",
        children: "#" + r.rank
      }), /*#__PURE__*/_jsx("text", {
        grow: true,
        color: "text",
        children: (AVATAR_GLYPH[r.avatar] || "👤") + " " + r.displayName
      }), /*#__PURE__*/_jsx("caption", {
        color: "muted",
        children: r.city ? r.city.name : ""
      }), /*#__PURE__*/_jsx("text", {
        color: "text",
        children: fmt(r.score)
      })]
    }, r.id));
  }
  return /*#__PURE__*/_jsxs("card", {
    gap: 6,
    children: [/*#__PURE__*/_jsx(Section, {
      children: "Leaderboard"
    }), rows]
  });
}
function __page__profile() {
  return /*#__PURE__*/_jsxs("column", {
    gap: 16,
    children: [/*#__PURE__*/_jsx(MyProfile, {}), /*#__PURE__*/_jsx(Leaderboard, {})]
  });
}

// ---- app/research/page.jsx ----
// app/research/page.jsx — the university research tree.

function TopicCard(props) {
  var t = props.topic;
  function start() {
    Api.action("/research/start", {
      topicKey: t.key
    }, function () {
      props.reload();
    });
  }
  var status = t.done ? "✅ Researched" : t.available ? "Available" : "🔒 Locked";
  return /*#__PURE__*/_jsxs("card", {
    gap: 6,
    children: [/*#__PURE__*/_jsxs("row", {
      gap: 8,
      children: [/*#__PURE__*/_jsx("title", {
        color: "text",
        children: "🔬 " + t.name
      }), /*#__PURE__*/_jsx("spacer", {}), /*#__PURE__*/_jsx("badge", {
        children: status
      })]
    }), /*#__PURE__*/_jsx("text", {
      wrap: true,
      color: "muted",
      children: t.description
    }), /*#__PURE__*/_jsxs("row", {
      gap: 12,
      wrap: true,
      children: [/*#__PURE__*/_jsx("caption", {
        color: "muted",
        children: "Cost: " + fmt(t.cost) + " pts"
      }), /*#__PURE__*/_jsx("caption", {
        color: "muted",
        children: "⏳ " + fmtDuration(t.time)
      }), /*#__PURE__*/_jsx("caption", {
        color: "muted",
        children: "🎓 University L" + t.requiresUniversity
      })]
    }), t.requires.length > 0 ? /*#__PURE__*/_jsx("caption", {
      color: "muted",
      children: "Needs: " + t.requires.join(", ")
    }) : null, /*#__PURE__*/_jsx("caption", {
      color: "primary",
      children: "Unlocks: " + t.unlocks
    }), !t.done && t.available ? /*#__PURE__*/_jsx("button", {
      kind: "filled",
      onPress: start,
      children: "Research"
    }) : null]
  });
}
function __page__research() {
  var g = useGame();
  var topics = useState([]);
  function reload() {
    Api.get("/research", function (list) {
      topics[1](list);
    });
  }
  useEffect(function () {
    reload();
  }, []);
  var active = null;
  for (var i = 0; i < g.state.jobs.length; i++) if (g.state.jobs[i].kind == "RESEARCH") active = g.state.jobs[i];
  var cards = [];
  for (var j = 0; j < topics[0].length; j++) cards.push(/*#__PURE__*/_jsx(TopicCard, {
    topic: topics[0][j],
    reload: reload
  }, topics[0][j].key));
  return /*#__PURE__*/_jsxs("column", {
    gap: 16,
    children: [/*#__PURE__*/_jsx(Section, {
      children: "Research tree"
    }), /*#__PURE__*/_jsx("caption", {
      color: "muted",
      children: "Research bank: " + fmt(g.state.city.researchBank) + " pts  (+" + fmt(g.state.economy.researchPerMin) + "/min)"
    }), active != null ? /*#__PURE__*/_jsx("card", {
      gap: 8,
      children: /*#__PURE__*/_jsxs("row", {
        gap: 8,
        children: [/*#__PURE__*/_jsx("text", {
          grow: true,
          color: "text",
          children: "🔬 Researching " + active.topicKey
        }), /*#__PURE__*/_jsx(Countdown, {
          endAt: active.endAt,
          onRush: function () {
            Api.post("/gems/fastforward", {
              kind: "job",
              id: active.id
            }, function () {
              Api.refreshState();
            });
          }
        })]
      })
    }) : null, cards]
  });
}

// ---- app/war/page.jsx ----
// app/war/page.jsx — the war ledger: ongoing marches/battles and past reports.

function RoundLine(props) {
  var l = props.entry;
  if (l.type == "engage") return /*#__PURE__*/_jsx("caption", {
    color: "muted",
    children: "⚔️ Engaged — attacker HP " + fmt(l.attackerHp) + " vs defender HP " + fmt(l.defenderHp)
  });
  if (l.type == "round") {
    var ac = Object.keys(l.attackerCasualties || {}).map(function (k) {
      return k + " -" + l.attackerCasualties[k];
    }).join(", ") || "none";
    var dc = Object.keys(l.defenderCasualties || {}).map(function (k) {
      return k + " -" + l.defenderCasualties[k];
    }).join(", ") || "none";
    return /*#__PURE__*/_jsx("caption", {
      color: "muted",
      children: "Round " + l.round + ": you lost [" + ac + "], enemy lost [" + dc + "] — left " + l.attackerLeft + " vs " + l.defenderLeft
    });
  }
  if (l.type == "end") {
    var loot = Object.keys(l.loot || {}).map(function (k) {
      return resIcon(k) + fmt(l.loot[k]);
    }).join(" ");
    return /*#__PURE__*/_jsx("caption", {
      color: "primary",
      children: "🏁 Winner: " + l.winner + (loot ? "  loot: " + loot : "")
    });
  }
  return null;
}
function WarCard(props) {
  var w = props.war;
  var lines = [];
  for (var i = 0; i < w.log.length; i++) lines.push(/*#__PURE__*/_jsx(RoundLine, {
    entry: w.log[i]
  }, i));
  var title = w.isAttacker ? "⚔️ Attacking " + w.defender : "🛡️ Defending vs " + w.attacker;
  var statusColor = w.winner == null ? "muted" : w.isAttacker == (w.winner == "attacker") ? "primary" : "danger";
  return /*#__PURE__*/_jsxs("card", {
    gap: 6,
    children: [/*#__PURE__*/_jsxs("row", {
      gap: 8,
      children: [/*#__PURE__*/_jsx("title", {
        color: "text",
        children: title
      }), /*#__PURE__*/_jsx("spacer", {}), /*#__PURE__*/_jsx("badge", {
        children: w.status
      })]
    }), /*#__PURE__*/_jsx("caption", {
      color: statusColor,
      children: w.status == "FINISHED" ? "Result: " + (w.winner || "—") : w.status == "MARCHING" ? "Marching…" : "Round " + w.round + " in progress"
    }), w.status != "FINISHED" && w.isAttacker ? /*#__PURE__*/_jsx(Countdown, {
      endAt: w.nextRoundAt,
      onRush: function () {
        Api.post("/gems/fastforward", {
          kind: "war",
          id: w.id
        }, function () {
          props.reload();
        });
      }
    }) : null, lines]
  });
}
function __page__war() {
  var wars = useState([]);
  function reload() {
    Api.get("/war", function (list) {
      wars[1](list);
    });
  }
  useEffect(function () {
    reload();
  }, []);
  var cards = [];
  for (var i = 0; i < wars[0].length; i++) cards.push(/*#__PURE__*/_jsx(WarCard, {
    war: wars[0][i],
    reload: reload
  }, wars[0][i].id));
  return /*#__PURE__*/_jsxs("column", {
    gap: 16,
    children: [/*#__PURE__*/_jsx(Section, {
      children: "Wars"
    }), cards.length ? cards : /*#__PURE__*/_jsx("caption", {
      color: "muted",
      children: "No campaigns yet. Attack a rival from the World map."
    })]
  });
}

// ---- app/world/page.jsx ----
// app/world/page.jsx — the 3D world map. Cities are shown as markers; clicking
// one opens a menu: send resources, attack, or open the owner's profile.

var RES = ["lumber", "food", "sulfur", "marble", "glass", "gold", "iron", "wine"];
function SendResources(props) {
  var amounts = useState({});
  function setAmt(k, v) {
    var next = {};
    var keys = Object.keys(amounts[0]);
    for (var i = 0; i < keys.length; i++) next[keys[i]] = amounts[0][keys[i]];
    next[k] = v;
    amounts[1](next);
  }
  function send() {
    var res = {};
    for (var i = 0; i < RES.length; i++) {
      var v = parseInt(amounts[0][RES[i]] || "0", 10);
      if (v > 0) res[RES[i]] = v;
    }
    Api.post("/market/send", {
      toCityId: props.city.id,
      resources: res
    }, function (r) {
      flash("Caravan dispatched — arrives in " + r.arriveInSeconds + "s", "success");
      props.onDone();
    });
  }
  var g = useGame();
  var rows = [];
  for (var i = 0; i < RES.length; i++) {
    var k = RES[i];
    rows.push(/*#__PURE__*/_jsxs("row", {
      gap: 8,
      children: [/*#__PURE__*/_jsx("text", {
        grow: true,
        color: "text",
        children: resIcon(k) + " " + resName(k) + " (have " + fmt(g.state.resources[k]) + ")"
      }), /*#__PURE__*/_jsx("input", {
        hint: "0",
        value: amounts[0][k] || "",
        onChange: function (kk) {
          return function (v) {
            setAmt(kk, v);
          };
        }(k)
      })]
    }, k));
  }
  return /*#__PURE__*/_jsxs("card", {
    gap: 8,
    children: [/*#__PURE__*/_jsx(Section, {
      children: "Send resources to " + props.city.name
    }), rows, /*#__PURE__*/_jsx("button", {
      kind: "filled",
      onPress: send,
      children: "Dispatch caravan"
    })]
  });
}
function AttackForm(props) {
  var g = useGame();
  var amounts = useState({});
  function setAmt(k, v) {
    var next = {};
    var keys = Object.keys(amounts[0]);
    for (var i = 0; i < keys.length; i++) next[keys[i]] = amounts[0][keys[i]];
    next[k] = v;
    amounts[1](next);
  }
  function attack() {
    var troops = {};
    for (var i = 0; i < g.state.troops.length; i++) {
      var t = g.state.troops[i];
      var v = parseInt(amounts[0][t.type] || "0", 10);
      if (v > 0) troops[t.type] = v;
    }
    Api.post("/war/declare", {
      defenderCityId: props.city.id,
      troops: troops
    }, function (r) {
      if (r.war != null) {
        flash("Army marches! Arrives in " + r.marchSeconds + "s", "success");
        props.onDone();
      }
    });
  }
  var rows = [];
  for (var i = 0; i < g.state.troops.length; i++) {
    var t = g.state.troops[i];
    if (t.count <= 0) continue;
    rows.push(/*#__PURE__*/_jsxs("row", {
      gap: 8,
      children: [/*#__PURE__*/_jsx("text", {
        grow: true,
        color: "text",
        children: troopIcon(t.type) + " " + t.type + " (have " + t.count + ")"
      }), /*#__PURE__*/_jsx("input", {
        hint: "0",
        value: amounts[0][t.type] || "",
        onChange: function (tt) {
          return function (v) {
            setAmt(tt, v);
          };
        }(t.type)
      })]
    }, t.type));
  }
  if (rows.length == 0) return /*#__PURE__*/_jsx("caption", {
    color: "danger",
    children: "You have no troops to send. Train some in the Army screen."
  });
  return /*#__PURE__*/_jsxs("card", {
    gap: 8,
    children: [/*#__PURE__*/_jsx(Section, {
      children: "Attack " + props.city.name
    }), rows, /*#__PURE__*/_jsx("button", {
      kind: "danger",
      onPress: attack,
      children: "March to war"
    })]
  });
}
function ProfileView(props) {
  var prof = useState(null);
  useEffect(function () {
    Api.get("/players/" + props.city.ownerId, function (p) {
      prof[1](p);
    });
  }, [props.city.ownerId]);
  if (prof[0] == null) return /*#__PURE__*/_jsx("caption", {
    color: "muted",
    children: "Loading profile\u2026"
  });
  var p = prof[0];
  return /*#__PURE__*/_jsxs("card", {
    gap: 6,
    children: [/*#__PURE__*/_jsxs("row", {
      gap: 8,
      children: [/*#__PURE__*/_jsx("title", {
        color: "text",
        children: "👤 " + p.displayName
      }), /*#__PURE__*/_jsx("spacer", {}), /*#__PURE__*/_jsx("badge", {
        children: "#" + p.rank
      })]
    }), /*#__PURE__*/_jsx("text", {
      wrap: true,
      color: "muted",
      children: p.bio || "This commander keeps their counsel."
    }), /*#__PURE__*/_jsx("caption", {
      color: "muted",
      children: "⭐ Score " + fmt(p.score)
    }), p.city != null ? /*#__PURE__*/_jsx("caption", {
      color: "muted",
      children: "🏙️ " + p.city.name + " @ (" + p.city.x + ", " + p.city.y + ")"
    }) : null]
  });
}
function CityMenu(props) {
  var mode = useState(null);
  var c = props.city;
  if (c.id == props.myCityId) {
    return /*#__PURE__*/_jsx("caption", {
      color: "primary",
      children: "🏰 " + c.name + " — this is your capital."
    });
  }
  return /*#__PURE__*/_jsxs("card", {
    gap: 8,
    children: [/*#__PURE__*/_jsxs("row", {
      gap: 8,
      children: [/*#__PURE__*/_jsx("title", {
        color: "text",
        children: "🏙️ " + c.name
      }), /*#__PURE__*/_jsx("spacer", {}), /*#__PURE__*/_jsx("caption", {
        color: "muted",
        children: c.owner
      })]
    }), /*#__PURE__*/_jsxs("row", {
      gap: 8,
      wrap: true,
      children: [/*#__PURE__*/_jsx("button", {
        kind: mode[0] == "send" ? "tonal" : "outline",
        onPress: function () {
          mode[1]("send");
        },
        children: "\uD83D\uDCE6 Send resources"
      }), /*#__PURE__*/_jsx("button", {
        kind: mode[0] == "attack" ? "tonal" : "danger",
        onPress: function () {
          mode[1]("attack");
        },
        children: "\u2694\uFE0F Attack"
      }), /*#__PURE__*/_jsx("button", {
        kind: mode[0] == "profile" ? "tonal" : "ghost",
        onPress: function () {
          mode[1]("profile");
        },
        children: "\uD83D\uDC64 Profile"
      })]
    }), mode[0] == "send" ? /*#__PURE__*/_jsx(SendResources, {
      city: c,
      onDone: function () {
        mode[1](null);
      }
    }) : null, mode[0] == "attack" ? /*#__PURE__*/_jsx(AttackForm, {
      city: c,
      onDone: function () {
        mode[1](null);
      }
    }) : null, mode[0] == "profile" ? /*#__PURE__*/_jsx(ProfileView, {
      city: c
    }) : null]
  });
}
function __page__world() {
  var g = useGame();
  var cities = useState([]);
  var selected = useState(null);
  var center = {
    x: g.state.city.x,
    y: g.state.city.y
  };
  useEffect(function () {
    Api.get("/world?cx=" + center.x + "&cy=" + center.y + "&r=40", function (list) {
      cities[1](list);
    });
  }, []);
  var rows = [];
  for (var i = 0; i < cities[0].length; i++) {
    var c = cities[0][i];
    rows.push(/*#__PURE__*/_jsx(CityRow, {
      city: c,
      mine: c.id == g.state.city.id,
      onSelect: function (cc) {
        return function () {
          selected[1](cc);
        };
      }(c),
      selected: selected[0] != null && selected[0].id == c.id
    }, c.id));
  }
  return /*#__PURE__*/_jsxs("column", {
    gap: 16,
    children: [/*#__PURE__*/_jsx(Section, {
      children: "World map"
    }), /*#__PURE__*/_jsx(WorldScene, {
      center: center,
      cities: cities[0],
      myCityId: g.state.city.id,
      selectedId: selected[0] != null ? selected[0].id : null,
      height: 400
    }), /*#__PURE__*/_jsx("caption", {
      color: "muted",
      children: "Your capital " + g.state.city.name + " @ (" + center.x + ", " + center.y + "). Nearby realms:"
    }), /*#__PURE__*/_jsx("card", {
      gap: 6,
      children: rows.length ? rows : /*#__PURE__*/_jsx("caption", {
        color: "muted",
        children: "No neighbours in view."
      })
    }), selected[0] != null ? /*#__PURE__*/_jsx(CityMenu, {
      city: selected[0],
      myCityId: g.state.city.id
    }) : null]
  });
}
function CityRow(props) {
  var c = props.city;
  return /*#__PURE__*/_jsxs("row", {
    gap: 8,
    children: [/*#__PURE__*/_jsx("text", {
      grow: true,
      color: props.selected ? "primary" : "text",
      children: (props.mine ? "🏰 " : "🏙️ ") + c.name + "  (" + c.x + ", " + c.y + ")"
    }), /*#__PURE__*/_jsx("caption", {
      color: "muted",
      children: c.owner
    }), /*#__PURE__*/_jsx("button", {
      kind: props.selected ? "tonal" : "ghost",
      onPress: props.onSelect,
      children: "Open"
    })]
  });
}

// ---- generated: file-based routing manifest + mount entry ----
var __VICTOR_ROUTES = [
  { path: "/market", component: __page__market },
  { path: "/military", component: __page__military },
  { path: "/", component: __page__index },
  { path: "/profile", component: __page__profile },
  { path: "/research", component: __page__research },
  { path: "/war", component: __page__war },
  { path: "/world", component: __page__world },
];
VictorClient.mountApp(_jsx(VictorApp, { routes: __VICTOR_ROUTES, layout: __layout__root, initial: "/" }), { design: [1280, 720], portrait: false, theme: "dark" });
