// =============================================================================
// gen_registry.dart — generate lib/registry.g.dart from Flutter's public API.
// =============================================================================
//
// This is the Flutter analogue of the Godot bridge's `tools/gen_global_constants.py`
// ("never written by hand"): it makes host-side widget coverage complete by
// GENERATING the registry from the framework's own API rather than enumerating
// widgets by hand. Because Flutter is AOT Dart with no runtime reflection, this
// is done at BUILD time with the analyzer instead of at runtime with ClassDB.
//
//   dart pub get
//   dart run tool/gen_registry.dart            # overwrites lib/registry.g.dart
//
// What it does:
//   1. Resolves the Flutter package (material/cupertino/widgets) with the
//      analyzer.
//   2. Finds every public class that is a `Widget` subtype with a usable
//      constructor, and every public enum.
//   3. Emits `buildGenerated(type, p, raw, key, it)` — a `switch (type)` that
//      constructs each widget by mapping its named constructor parameters from
//      the incoming props through the type-directed decoders on `_P`
//      (`p.w`/`p.wl`/`p.d`/`p.s`/`p.color`/`p.edge`/`p.onTap`/…), plus a
//      `child`/`children` hookup from `raw`.
//   4. Emits an enum-name resolver so any enum-typed parameter decodes from a
//      string.
//
// Parameters whose type it cannot map (exotic value types, controllers,
// builders needing a BuildContext, etc.) are left at their default — the widget
// still constructs, and the hand-written catalog in main.dart already covers the
// cases that need bespoke wiring (event widgets, scaffolds, buttons). The result
// is that ANY public widget is reachable by name from the guest with no manual
// per-widget code.
//
// This tool depends on `package:analyzer`; add it under dev_dependencies and run
// with a Flutter SDK on PATH. It is intentionally NOT part of the app itself.

import 'dart:io';

import 'package:analyzer/dart/analysis/analysis_context_collection.dart';
import 'package:analyzer/dart/analysis/results.dart';
import 'package:analyzer/dart/element/element.dart';
import 'package:analyzer/dart/element/type.dart';

/// The framework libraries whose public widgets we expose.
const _entryLibraries = <String>[
  'package:flutter/material.dart',
  'package:flutter/cupertino.dart',
  'package:flutter/widgets.dart',
];

Future<void> main(List<String> args) async {
  final sdkLib = _flutterPackageLib();
  if (sdkLib == null) {
    stderr.writeln('Could not locate the Flutter package. Run `flutter pub get` first '
        'and invoke with a Flutter SDK on PATH.');
    exit(2);
  }

  final collection = AnalysisContextCollection(includedPaths: [sdkLib]);
  final widgets = <String, _WidgetInfo>{};
  final enums = <String, List<String>>{};

  for (final ctx in collection.contexts) {
    final session = ctx.currentSession;
    for (final path in ctx.contextRoot.analyzedFiles()) {
      if (!path.endsWith('.dart')) continue;
      final result = await session.getResolvedLibrary(path);
      if (result is! ResolvedLibraryResult) continue;
      final lib = result.element;
      for (final cls in lib.topLevelElements.whereType<ClassElement>()) {
        if (cls.isPrivate || cls.isAbstract) continue;
        if (!_isWidget(cls.thisType)) continue;
        final ctor = _bestConstructor(cls);
        if (ctor == null) continue;
        widgets.putIfAbsent(cls.name, () => _WidgetInfo(cls.name, ctor, enums));
      }
      for (final en in lib.topLevelElements.whereType<EnumElement>()) {
        if (en.isPrivate) continue;
        enums.putIfAbsent(en.name, () => en.fields.where((f) => f.isEnumConstant).map((f) => f.name).toList());
      }
    }
  }

  final out = StringBuffer()
    ..writeln('// GENERATED by tool/gen_registry.dart — do not edit by hand.')
    ..writeln('// The full public Flutter widget/enum registry.')
    ..writeln()
    ..writeln("part of 'main.dart';")
    ..writeln()
    ..writeln('Widget? buildGenerated(String type, _P p, List raw, Key? key, _Interp it) {')
    ..writeln('  switch (type) {');

  final names = widgets.keys.toList()..sort();
  for (final name in names) {
    out.writeln("    case '$name':");
    out.writeln('      return ${widgets[name]!.construct()};');
  }

  out
    ..writeln('    default:')
    ..writeln('      return null;')
    ..writeln('  }')
    ..writeln('}')
    ..writeln()
    ..writeln('// Resolve any enum value from a string name.')
    ..writeln('Object? _enum(String kind, String? name) {')
    ..writeln('  if (name == null) return null;')
    ..writeln('  switch (kind) {');
  final enumNames = enums.keys.toList()..sort();
  for (final e in enumNames) {
    out.writeln("    case '$e':");
    out.writeln('      switch (name) {');
    for (final v in enums[e]!) {
      out.writeln("        case '$v': return $e.$v;");
    }
    out.writeln('        default: return null;');
    out.writeln('      }');
  }
  out
    ..writeln('    default: return null;')
    ..writeln('  }')
    ..writeln('}');

  File('lib/registry.g.dart').writeAsStringSync(out.toString());
  stdout.writeln('Wrote lib/registry.g.dart: ${widgets.length} widgets, ${enums.length} enums.');
}

/// One widget class + the constructor we build it from.
class _WidgetInfo {
  _WidgetInfo(this.name, this.ctor, this.enums);
  final String name;
  final ConstructorElement ctor;
  final Map<String, List<String>> enums;

  /// Emit a Dart expression constructing this widget from `p`/`raw`.
  String construct() {
    final args = <String>['key: key'];
    for (final param in ctor.parameters) {
      if (!param.isNamed) continue; // positional required params: left to defaults
      final expr = _mapParam(param);
      if (expr != null) args.add('${param.name}: $expr');
    }
    return '$name(${args.join(', ')})';
  }

  /// Map one named parameter's type to a `_P` accessor, or null to skip it.
  String? _mapParam(ParameterElement param) {
    final n = "'${param.name}'";
    final t = param.type;
    final tn = t.getDisplayString(withNullability: false);

    // child / children get their content from the node's real children first,
    // falling back to a widget-valued prop.
    if (param.name == 'child' && _isWidgetType(t)) {
      return 'raw.isEmpty ? p.w($n) : it.build(raw.first)';
    }
    if (param.name == 'children' && tn.startsWith('List<')) {
      return 'raw.isNotEmpty ? raw.map<Widget>((e) => it.build(e)).toList() : (p.wl($n) ?? const <Widget>[])';
    }

    if (_isWidgetType(t)) return 'p.w($n)';
    if (tn == 'List<Widget>') return 'p.wl($n)';
    if (tn == 'String') return 'p.s($n)';
    if (tn == 'bool') return 'p.b($n)';
    if (tn == 'int') return 'p.i($n)';
    if (tn == 'double') return 'p.d($n)';
    if (tn == 'Color') return 'p.color($n)';
    if (tn == 'EdgeInsetsGeometry' || tn == 'EdgeInsets') return 'p.edge($n)';
    if (tn == 'Duration') return 'p.duration($n)';
    if (tn == 'AlignmentGeometry' || tn == 'Alignment') return 'p.align($n)';
    if (tn == 'VoidCallback') return "p.onTap($n)";
    if (tn == 'ValueChanged<bool>') return "p.onBool($n)";
    if (tn == 'ValueChanged<int>') return "p.onInt($n)";
    if (tn == 'ValueChanged<double>') return "p.onDouble($n)";
    if (tn == 'ValueChanged<String>') return "p.onString($n)";

    // Enum-typed parameter: decode by name, cast back to the enum.
    if (enums.containsKey(tn)) return "_enum('$tn', p.s($n)) as $tn?";

    return null; // unmapped type → leave at the constructor default
  }
}

bool _isWidgetType(DartType t) {
  final n = t.getDisplayString(withNullability: false);
  return n == 'Widget' || n == 'PreferredSizeWidget';
}

bool _isWidget(InterfaceType t) {
  for (final s in [t, ...t.allSupertypes]) {
    if (s.element.name == 'Widget') return true;
  }
  return false;
}

/// Prefer the unnamed generative constructor with the most named parameters
/// (typically the canonical one); skip factory-only / const-asset widgets we
/// cannot map.
ConstructorElement? _bestConstructor(ClassElement cls) {
  ConstructorElement? best;
  var bestScore = -1;
  for (final c in cls.constructors) {
    if (c.isPrivate) continue;
    final named = c.parameters.where((p) => p.isNamed).length;
    final requiredPositional = c.parameters.where((p) => p.isRequiredPositional).length;
    // We can only satisfy up to a leading `child`-like positional; skip ctors
    // with unmappable required positionals.
    if (requiredPositional > 1) continue;
    if (named > bestScore) {
      best = c;
      bestScore = named;
    }
  }
  return best;
}

/// Best-effort resolution of the Flutter package's `lib/` directory via
/// `.dart_tool/package_config.json` in the current app.
String? _flutterPackageLib() {
  final cfg = File('.dart_tool/package_config.json');
  if (!cfg.existsSync()) return null;
  final text = cfg.readAsStringSync();
  final match = RegExp(r'"name"\s*:\s*"flutter"\s*,\s*"rootUri"\s*:\s*"([^"]+)"').firstMatch(text);
  if (match == null) return null;
  var uri = match.group(1)!;
  // rootUri is usually relative to .dart_tool/.
  final resolved = uri.startsWith('file://')
      ? Uri.parse(uri).toFilePath()
      : File('.dart_tool/$uri').absolute.path;
  final lib = Directory('$resolved/lib');
  return lib.existsSync() ? lib.path : resolved;
}
